name: Deploy Lambda via S3 #test

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1                  # change if needed
      S3_BUCKET: weatherbucket               # 🔁 replace this
      S3_KEY: lambda/function.zip            # S3 key path
      LAMBDA_NAME: myweatherapp              # 🔁 replace this

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies and build package
      run: |
        pip install -r requirements.txt -t package
        cp lambda_function.py weather.py package/
        cd package
        zip -r ../function.zip .
        cd ..

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Upload ZIP to S3
      run: |
        aws s3 cp function.zip s3://${{ env.S3_BUCKET }}/${{ env.S3_KEY }}

    - name: Deploy Lambda from S3
      run: |
        aws lambda update-function-code \
          --function-name ${{ env.LAMBDA_NAME }} \
          --s3-bucket ${{ env.S3_BUCKET }} \
          --s3-key ${{ env.S3_KEY }}
