name: Deploy Lambda

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies and build package
      run: |
        pip install -r requirements.txt -t package
        cp lambda_function.py weather.py package/
        cd package
        zip -r ../function.zip .

    - name: Deploy to AWS Lambda
      uses: aws-actions/aws-lambda-deploy@v1
      with:
        function-name: weathertest
        zip-file: function.zip
        role: arn:aws:iam::<account_id>:role/<lambda-execution-role>
        handler: lambda_function.lambda_handler
        runtime: python3.11
        timeout: 30

    - name: Clean up
      run: rm -rf package function.zip
